### ISSUE TITLE
Blocky shadow when camera projection is orthogonal

### ISSUE THREAD

**Issue by farahats9** [GDQuest/godot-3d-dodge-the-creeps#11]
The shadows are separated and not continuous, this happens only in orthogonal projection camera, if I change it to prespective it works fine. 
The tutorial is suggesting making camera `Far` property to 100 but that didn't fix the issue.
I found this related issue in godot repo [#73472](https://github.com/godotengine/godot/issues/73472) and [#58332](https://github.com/godotengine/godot/issues/58332)

![image](https://github.com/godotengine/godot-3d-dodge-the-creeps/assets/463359/828b4c43-0cfe-4d3f-a9e9-7b3b7ea1d263)

**Comment by farahats9** [comment]
I found a fix for the problem, set the `Pancake Size` to 0 in the DirectionalLight3D -> directional shadow.
No idea why this fixed the problem but it did.

**Comment by jgao222** [comment]
I also encountered this issue. The `Pancake Size` fix worked for me. Strangely, it also worked to *maximize the screen*.
