### ISSUE TITLE
Collision with the same mob is detected multiple times

### ISSUE THREAD

**Issue by farahats9** [GDQuest/godot-3d-dodge-the-creeps#12]
When jumping on a mob the collision is sometimes detected 2 or 3 times which fires the squash signal multiple times and causes the score to increase 2 or 3 instead of 1.
the problem appears to be in this part of the code

```gdscript
# player.gd
func _physics_process(delta):
        #....
	# Iterate through all collisions that occurred this frame
	for index in range(get_slide_collision_count()):
		# We get one of the collisions with the player
		var collision = get_slide_collision(index)
		# If the collision is with ground
		if (collision.get_collider() == null):
			continue
		# If the collider is with a mob
		if collision.get_collider().is_in_group("mob"):
			var mob = collision.get_collider()
			# we check that we are hitting it from above.
			if Vector3.UP.dot(collision.get_normal()) > 0.1:
				# If so, we squash it and bounce.
				mob.squash()
				target_velocity.y = bounce_impulse
```

It appears the `get_slide_collision_count()` is counting multiple collisions with the same mob instead of counting it only once.
Does anyone know how to avoid this?
I thought of tracking last squashed mob and ignoring it in the next iteration of the loop but that doesn't sound elegant, there must be some setting or trick that I am missing.

**Comment by ParadoxV5** [comment]
> is counting multiple collisions with the same mob instead of counting it only once

I believe it’s because of colliding with entities that are queued for but not yet freed.
Godot 4’s better than detecting collision thrice on the same pair of entities, right?

Use `is_queued_for_deletion()` to check if a mob is in that zombie state. Example: 373ee51

**Comment by farahats9** [comment]
> Use `is_queued_for_deletion()`

awesome that fixed my problem!
