### ISSUE TITLE
Update statuses and archive this repository – Project moved to `godot-demo-projects`

### ISSUE THREAD

**Issue by ParadoxV5** [GDQuest/godot-3d-dodge-the-creeps#14]
*Originally posted by @ParadoxV5 in https://github.com/godotengine/godot-3d-dodge-the-creeps/issues/13#issuecomment-1815211635*

> The project has been fully integrated into the [demo projects](https://github.com/godotengine/godot-demo-projects) and is maintained there now
> ⸺ @AThousandShips

godotengine/godot-demo-projects#884 for Godot 4 has superceded this Godot 3 repository, yet neither this repository nor [the docs’ tutorial](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/01.game_setup.html#setting-up-the-game-area) were made aware.
I request archiving this repository after updating its status on the README. ~~The docs’ tutorial also needs an update to go off the new project (while the assets need no update, the template project does – https://github.com/ParadoxV5/godot-3d-squash-the-creeps/releases/2.0.0).~~ __https://github.com/godotengine/godot-docs/issues/6744#issuecomment-1815242987__

Supercedes, i.e. closes #6, #8, #9, #10, #13

**Comment by akien-mga** [comment]
Thanks for the contribution! This project is archived and replaced by https://github.com/godotengine/godot-demo-projects/tree/master/3d/squash_the_creeps, please contribute there instead!
