### ISSUE TITLE
Doesn't work with Godot 4

### ISSUE THREAD

**Issue by vernon99** [GDQuest/godot-3d-dodge-the-creeps#6]
Shows a bunch of errors both on load and on executing. Since this is my first Godot tutorial I was trying to use, hard to give you more specific information.

**Comment by Cerno-b** [comment]
Seems to work for me (Godot 4.2 head self-compiled). I get an info message that the project has been built with Godot 3. I chose to convert everything to Godot 4 and so far it looks like it works. I am currently following the 3D-tutorial and will check in again if I find anything that does not work.

It would be nice to release a version of this project that is compatible with Godot 4 to make it less confusing for beginners who might not know what to do with the conversion warning.

**Comment by akien-mga** [comment]
Thanks for the contribution! This project is archived and replaced by https://github.com/godotengine/godot-demo-projects/tree/master/3d/squash_the_creeps, please contribute there instead!
